### ISSUE TITLE
Error #37 Invalid application - no unmount function

### ISSUE THREAD

**Issue by zeskysee** [CanopyTax/single-spa-svelte#7]
Hi when I try using single-spa-svelte with svelte (3.0.0) & latest root config created (single-spa@5.1.1) from create-single-spa cli , shows the following error in console log:

![error](https://user-images.githubusercontent.com/6244226/76396644-8d0e2900-63b4-11ea-9a60-0820472c425f.PNG)

When try to to debug in browser console, shows as following:

![console-log](https://user-images.githubusercontent.com/6244226/76396659-90a1b000-63b4-11ea-86b7-9c4a504b9efb.PNG)

My Root Config:
```
import { registerApplication, start } from "single-spa";
import * as isActive from "./activity-functions";

registerApplication(
  "@exp/navbar",
  () => System.import("@exp/navbar"),
  isActive.navbar
);
```

After I try the recommend fix from the https://single-spa.js.org/error/?code=37, it still not working.

**Comment by internettrans** [comment]
Hi @zeskysee - could you show the contents of the entry file for `@exp/navbar`? Also, are you using webpack or rollup to compile the project?

**Comment by zeskysee** [comment]
Sorry for the late reply, after investigate the webpack.config find out is my mistake. I forget to point the entry from main to the newly created entry file.
